Update CI

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -1,16 +1,15 @@
-ARG UBUNTU_RELESE=noble
-ARG MANYPYTHON_BASE_IMAGE=manypython-base
-
-FROM $MANYPYTHON_BASE_IMAGE:$UBUNTU_RELESE
+ARG BASE_IMAGE="mtkn1.ghcr.io/manypython-image"
+ARG VARIANT="noble"
+FROM $BASE_IMAGE:${VARIANT}
 
 LABEL dev.containers.features="common"
 
-ARG UBUNTU_RELESE
-RUN if [ "$UBUNTU_RELESE" = "noble" ]; then \
+ARG VARIANT
+RUN if [ "$VARIANT" = "noble" ]; then \
         if id "ubuntu" &>/dev/null; then \
-            echo "Deleting user 'ubuntu'  for $UBUNTU_RELESE" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $UBUNTU_RELESE"; \  
+            echo "Deleting user 'ubuntu'  for $VARIANT" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for $VARIANT"; \  
         else \
-            echo "User 'ubuntu' does not exist for $UBUNTU_RELESE"; \ 
+            echo "User 'ubuntu' does not exist for $VARIANT"; \ 
         fi; \
     fi
 
